### PR TITLE
format code && lua module autocomlete && lua module snippets

### PR DESCRIPTION
**Pull request by tiansin**
some snippets from: https://marketplace.visualstudio.com/items?itemName=jiejie.Lua-Nginx-Snippets

### CODE REVIEW

**Comment by hangxingliu** [comment]
I have read your code roughly. I marked some place via Github review.

And do you have the scripts to update lua directives likes [utils/download_hint_data.js](utils/download_hint_data.js)

**Comment by tiansin** [comment]
@hangxingliu 
Do some optimization for the suggestion, thank you.

**Comment by hangxingliu** [comment]
@tiansin I am very glad that you can continue to optimize. And is there any website we could make a automatic script to update Lua hint/completion data? 

And I found another problem: the the language of snippet's description in `snippets_lua` is Chinese. Do you have any good idea about it's i18n?

**Comment by tiansin** [comment]
@hangxingliu The generator is written in a mess.

**Comment by tiansin** [comment]
@hangxingliu  A lot of changes were made and generated using code snippets that I wrote myself.

**Comment by hangxingliu** [comment]
I will review and merge it as soon after finish my work

**Comment by hangxingliu** [comment]
@tiansin Because I don't have too much time to maintain this project in daily time. And I think you are good at Nginx and Lua. So if you want to be the collaborators of this project, you can contact to me via email or other IM software. (My email: <hangxingliu@gmail.com>)

**Comment by hangxingliu** [comment]
@tiansin Because I don't have too much time to maintain this project in daily time. And I think you are good at Nginx and Lua. So if you want to be the collaborators of this project, you can contact to me via email or other IM software. (My email: <hangxingliu@gmail.com>)

**Pull request merged**
