### PR TITLE
fix(syntaxes): update nginx syntax highlighting 💅🏻

### PR DESCRIPTION
**Pull request by latipun7**
This pull details the following:

- add an example file
- fix bug on donwload script
- update syntaxes with download script

Before:
before

After:
after

closes: #15

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Great work @latipun7. @hangxingliu can we get this merged? Thanks.

**Comment by ahmadalli** [comment]
any update on this?

**Comment by ahmadalli** [comment]
since this repo seems to be left unmaintained, I merged this to my own fork of this project https://github.com/ahmadalli/vscode-nginx-conf

**Comment by hangxingliu** [comment]
Thanks for your contribution. I leave a long time. I will merge this PR and release the new version in recent

**Comment by hangxingliu** [comment]
I will release a new version after I tested this extension at local and SSH remote.

**Pull request merged**
